# See http://www.appveyor.com/docs/appveyor-yml for many more options

# Skip on updates to the readme.
# We can force this by adding [skip ci] or [ci skip] anywhere in commit message 
skip_commits:
  message: /updated readme.*/
os: WMF 5S

build: false

test_script:
# Test with native PS version
  - ps: Invoke-Pester